# POST to /products/create with a random UUID
POST http://localhost:8080/products/create
Content-Type: application/json

{
  "id": "{{uuidf}}",
  "name": "Product 1x",
  "price": 150,
  "quantity": 15
}

### Generate UUID
@uuid = {{uuid}}