# POST to /products/create
POST http://localhost:8080/products/create
Content-Type: application/json

{
  "name": "Product 1",
  "price": 150,
  "quantity": 15,
  "category": "Category 1",
  "description": "Description 1"
}