### Constructing HMAC from request body with crypto
POST http://localhost:8080/products/create
Content-Type: application/json

{
  "id": "{{$random.uuid}}",
  "name": "Product {{$random.alphanumeric(11)}}",
  "price": {{$random.float()}},
  "quantity": {{$random.integer()}}
}


